const models = {
   users: Object.freeze({
      afk: -1,
      afkReason: '',
      afkObj: {},
      banned: false,
      ban_temporary: 0,
      ban_times: 0,
      point: 0,
      balance: 0,
      pocket: 0,
      deposito: 0,
      guard: 0,
      lastclaim: 0,
      lastrob: 0,
      premium: false,
      expired: 0,
      lastnotified: 0,
      lastseen: 0,
      hit: 0,
      warning: 0,
      attempt: 0,
      code: '',
      codeExpire: 0,
      email: '',
      verified: false,
      taken: false,
      partner: ''
   }),
   players: Object.freeze({
      exp: 1000,
      agility: 0,
      strength: 0,
      defense: 0,
      health: 100,
      stamina: 0,
      lucky: 1,
      inventory: {},
      resource: {
         potion: 10,
         wood: 0,
         rock: 0,
         iron: 0,
         string: 0,
         diamond: 0,
         emerald: 0,
         gold: 0,
         trash: 0,
         thread: 0,
         legendary: 0,
         mythic: 0,
         superior: 0,
         common: 0,
         uncommon: 0,
         fish: 0,
         bone: 0,
         carrot: 0,
         rat: 0,
         fire: 0
      },
      pets: [],
      tools: [],
      location: 0,
      clan: 0,
      last: {
         daily: 0,
         weekly: 0,
         monthly: 0,
         adventure: 0,
         dungeon: 0,
         robbing: 0,
         mining: 0,
         feeding: 0,
         gym: 0
      },
      berserker: {
         lose: 0,
         winner: 0,
         last: 0
      },
      petbattle: {
         lose: 0,
         winner: 0
      },
      quest: []
   }),
   groups: Object.freeze({
      activity: 0,
      antibot: true,
      antiporn: false,
      antidelete: true,
      antilink: false,
      antitagsw: true,
      antivirtex: false,
      adminonly: false,
      captcha: false,
      filter: false,
      game: true,
      mysterybox: true,
      left: false,
      localonly: false,
      mute: false,
      viewonce: false,
      autosticker: true,
      restrict: true,
      member: {},
      text_left: '',
      text_welcome: '',
      welcome: true,
      expired: 0,
      lastnotified: 0,
      stay: false
   }),
   chats: Object.freeze({
      chat: 0,
      lastseen: 0
   }),
   setting: Object.freeze({
      autodownload: true,
      antispam: true,
      debug: false,
      games: true,
      verify: false,
      levelup: false,
      mimic: [],
      error: [],
      hidden: [],
      pluginDisable: [],
      pluginVerified: [],
      receiver: [],
      except: [],
      groupmode: false,
      sk_pack: '𝙏𝙚𝙘𝙝𝙁𝙞𝙭 🅥❹.❶',
      sk_author: 'Techfix Solutions',
      self: false,
      noprefix: false,
      multiprefix: true,
      prefix: ['.', '#', '!', '/'],
      toxic: ["g0re", "g0r3", "g.o.r.e", "sap0", "sap4", "malparido", "malparida", "malparidos", "malparidas", "m4lp4rid0", "m4lp4rido", "m4lparido", "malp4rido", "m4lparid0", "malp4rid0", "chocha", "chup4la", "chup4l4", "chupalo", "chup4lo", "chup4l0", "chupal0", "chupon", "chupameesta", "sabandija", "hijodelagranputa", "hijodeputa", "hijadeputa", "hijadelagranputa", "kbron", "kbrona", "cajetuda", "laconchadedios", "putita", "putito", "put1t4", "putit4", "putit0", "put1to", "put1ta", "pr0stitut4s", "pr0stitutas", "pr05titutas", "pr0stitut45", "prostitut45", "prostituta5", "pr0stitut45", "fanax", "f4nax", "drogas", "droga", "dr0g4", "nepe", "p3ne", "p3n3", "pen3", "p.e.n.e", "pvt0", "pvto", "put0", "hijodelagransetentamilparesdeputa", "Chingadamadre", "coño", "c0ño", "coñ0", "c0ñ0", "afeminado", "drog4", "cocaína", "marihuana", "chocho", "chocha", "cagon", "pedorro", "agrandado", "agrandada", "pedorra", "cagona", "pinga", "joto", "sape", "mamar", "chigadamadre", "hijueputa", "chupa", "caca", "bobo", "boba", "loco", "loca", "chupapolla", "estupido", "estupida", "estupidos", "polla", "pollas", "idiota", "maricon", "chucha", "verga", "vrga", "naco", "zorra", "zorro", "zorras", "zorros", "pito", "huevon", "huevona", "huevones", "rctmre", "mrd", "ctm", "csm", "cepe", "sepe", "sepesito", "cepecito", "cepesito", "hldv", "ptm", "baboso", "babosa", "babosos", "babosas", "feo", "fea", "feos", "feas", "mamawebos", "chupame", "bolas", "qliao", "imbecil", "embeciles", "kbrones", "cabron", "capullo", "carajo", "gore", "gorre", "gorreo", "gordo", "gorda", "gordos", "gordas", "sapo", "sapa", "puto", "puta", "mierda", "cerdo", "cerda", "puerco", "puerca", "perra", "perro", "dumb", "fuck", "shit", "bullshit", "cunt", "semen", "bitch", "motherfucker", "foker", "fucking"],
      online: true,
      onlyprefix: '+',
      owners: ['573012686632'],
      moderators: ['573012686632'],
      lastReset: new Date * 1,
      msg: '◦ *Base de datos* : +db\nʜɪ +tag 👋🏻\n\n> ʏᴏ ꜱᴏʏ ᴛᴇᴄʜғɪx, ᴜɴ ᴀᴠᴀɴᴢᴀᴅᴏ ᴀsɪsᴛᴇɴᴛᴇ ᴅɪɢɪᴛᴀʟ ᴅᴇ ʟᴀ ᴏᴛʀᴀ ᴅɪᴍᴇɴsɪóɴ ᴅᴇ ʟᴏs sɪsᴛᴇᴍᴀs. ᴄʀᴇᴀᴅᴏ ᴅᴇsᴅᴇ ᴇʟ ɴúᴄʟᴇᴏ ᴏʟᴠɪᴅᴀᴅᴏ ᴅᴇʟ ᴄóᴅɪɢᴏ ʏ ᴇɴᴄᴀɴᴛᴀᴅᴏ ᴄᴏɴ ᴄᴏɴᴏᴄɪᴍɪᴇɴᴛᴏ ᴛʀᴀsᴄᴇɴᴅᴇɴᴛᴀʟ, ᴍɪ ᴍɪsɪóɴ ᴇs ᴀʏᴜᴅᴀʀᴛᴇ ᴄᴏɴ ɪɴғᴏʀᴍᴀᴄɪóɴ, ʀᴇᴄᴏᴘɪʟᴀᴄɪóɴ ᴅᴇ ᴅᴀᴛᴏs ʏ ғᴜɴᴄɪᴏɴᴀʟɪᴅᴀᴅ.',
      style: 4,
      rules: '-',
      cover: 'https://er.educause.edu/-/media/images/articles/2024/04/er24_041_headerart_1600x900.jpg',
      link: 'https://chat.whatsapp.com/LeyQI5YKnAK7QDTC6n2X3I',
      inbound: 0,
      outbound: 0
   }),
   setup: {
      operators: []
   },
   def_props: Object.freeze({
      users: [],
      chats: [],
      groups: [],
      setting: {},
      statistic: {},
      sticker: {},
      storage: []
   })
}

module.exports = { models }